HomeTrader.Web/Models/CompanyVM/CompaniesListViewModel.cs
using HomeTrader.Data.Models.Companies;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTrader.Models.CompanyVM
{
    public class CompaniesListViewModel
    {
        public IEnumerable<GpwCompany> Companies { get; set; }
       
        public readonly GpwCompany CompaniesName = new GpwCompany();
    }
}

HomeTrader.Web/Models/DetailsVM/BalanceVM.cs
using HomeTrader.Data.Models.Finance;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTrader.Models.DetailsVM
{
    public class BalanceVM
    {
        public int CompanyId { get; set; }
        public IEnumerable<FinanceBalance> BalanceRaports { get; set; }

        public readonly FinanceBalance BalanceColumnDescription = new FinanceBalance();

    }
}

HomeTrader.Web/Models/DetailsVM/CashFlowVM.cs
using HomeTrader.Data.Models.Finance;
using System.Collections.Generic;

namespace HomeTrader.Models.DetailsVM
{
    public class CashFlowVM
    {
        public int CompanyId { get; set; }
        public IEnumerable <FinanceCashFlow> CashFlowRaports { get; set; }

        public readonly FinanceCashFlow CashFlowColumnDescription = new FinanceCashFlow();


    }
}

HomeTrader.Web/Models/DetailsVM/IndexVM.cs
using HomeTrader.Data.Models.Companies;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HomeTrader.Models.DetailsVM
{
    public class IndexVM
    {
        public int CompanyId { get; set; }
        public GpwCompany Company { get; set; }
    }
}

HomeTrader.Web/Models/DetailsVM/ProfitAndLoseVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using HomeTrader.Data.Models.Finance;

namespace HomeTrader.Models.DetailsVM
{
    public class ProfitAndLoseVM
    {
        public int CompanyId { get; set; }
        public IEnumerable<FinanceProfitAndLose> ProfitAndLoseRaports { get; set; }

        public readonly FinanceProfitAndLose ProfitAndLoseDescription = new FinanceProfitAndLose();
    }
}

HomeTrader.Web/Models/ErrorViewModel.cs
using System;

namespace HomeTrader.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HomeTrader.Web/Controllers/CompanyController.cs
using HomeTrader.Data;
using HomeTrader.Models.CompanyVM;
using HomeTrader.Models.DetailsVM;
using Microsoft.AspNetCore.Mvc;

namespace HomeTrader.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompany _companyService;

        public CompanyController(ICompany companyService)
        {
            _companyService = companyService;
        }

        //GET - all companies
        public IActionResult Index()
        {

            CompaniesListViewModel companiesListVM = new CompaniesListViewModel()
            {
                Companies = _companyService.GetAllCompanies()
            };

            return View("Company",companiesListVM);
        }

        // GET - Company by Wig Index
        public IActionResult IndexSort(int id)
        {
            CompaniesListViewModel sortCompaniesListVM = new CompaniesListViewModel()
            {
                Companies = _companyService.SortCompaniesByIndex(id)
            };

            return View("Company",sortCompaniesListVM); 
        }


    }
}

HomeTrader.Web/Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTrader.Data;
using HomeTrader.Models.DetailsVM;
using Microsoft.AspNetCore.Mvc;

namespace HomeTrader.Controllers
{
    public class DetailsController : Controller
    {
        private readonly IFinance _financeService;
        private readonly ICompany _companyService;
        

        public DetailsController(IFinance financeService, ICompany companyService)
        {
            _financeService = financeService;
            _companyService = companyService;
        }

        // GET - tutaj wypisac pobranie podstawowych danych o spolce
        public IActionResult Index(int id)
        {

            return View("Index");
        }

        public IActionResult GetCashFlow(int id)
        {
            CashFlowVM CashFlowRaportVM = new CashFlowVM()
            {
                CompanyId = id,
                CashFlowRaports = _financeService.GetCashFlowRaportsByCompanyId(id)
            };

            return View("CashFlow", CashFlowRaportVM);
        }

        public IActionResult GetBalance(int id)
        {
            BalanceVM BalanceRaportVM = new BalanceVM
            {
                CompanyId = id,
                BalanceRaports = _financeService.GetBalanceRaportsByCompanyId(id)
            };

            return View("Balance", BalanceRaportVM);
        }

        public IActionResult GetProfitAndLose(int id)
        {
            ProfitAndLoseVM ProfitAndLoseRaportVM = new ProfitAndLoseVM
            {
                CompanyId = id,
                ProfitAndLoseRaports = _financeService.GetProfitAndLoseRaportsByCompanyId(id)
            };

            return View("ProfitAndLose", ProfitAndLoseRaportVM);
        }

        // Company controller part

        public IActionResult Company(int id)
        {
            IndexVM CompanyInfoVM = new IndexVM
            {
                CompanyId = id,
                Company = _companyService.GetCompanyById(id)

            };
            return View("Index", CompanyInfoVM);
        }

    }
}

HomeTrader.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HomeTrader.Models;

namespace HomeTrader.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HomeTrader.Web/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HomeTrader.Data;
using HomeTrader.Models.DetailsVM;
using Microsoft.AspNetCore.Mvc;

namespace HomeTrader.Controllers
{
    public class IndexController : Controller
    {
        private readonly ICompany _companyService;

        public IndexController(ICompany companyService)
        {
            _companyService = companyService;
        }


        public IActionResult Index(int id)
        {
            IndexVM CompanyInfoVM = new IndexVM
            {
                CompanyId = id,
                Company = _companyService.GetCompanyById(id)

            };
            return View("Index", CompanyInfoVM);
        }
    }
}

HomeTrader.Web/Views/Company/Company.cshtml
@model HomeTrader.Models.CompanyVM.CompaniesListViewModel

@{
    ViewData["Title"] = "Company";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <partial name="_CompaniesMenuButtons" />
</div>

<br />
<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <div class="row">
        <div class="col-6">
            <h6 class="text">Spółki Gpw</h6>
        </div>
    </div>
</div>
<br />
<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <table class="table table-striped border">
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.CompaniesName.Name)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.CompaniesName.Ticker)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.CompaniesName.Index)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.CompaniesName.ISIN)
            </th>
        </tr>
        @foreach (var company in Model.Companies)
        {
            <tr>
                <td>
                    <a asp-controller="Details" asp-action="Company" asp-route-id="@company.Id">
                        @Html.DisplayFor(m => company.Name)
                    </a>
                </td>
                <td>
                    @Html.DisplayFor(m => company.Ticker)
                </td>
                <td>
                    @Html.DisplayFor(m => company.Index)
                </td>
                <td>
                    @Html.DisplayFor(m => company.ISIN)
                </td>
            </tr>
        }
    </table>
</div>

HomeTrader.Web/Views/Details/Balance.cshtml
@model HomeTrader.Models.DetailsVM.BalanceVM
@{
    ViewData["Title"] = "Balance";
}

<h6>Balans</h6>
<br />
<div class="row">
    <partial name="_DetailsMenuButtons" model="@Model.CompanyId" />
</div>
<br />
<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <div class="row">
        <div class="col-6">
            <h6 class="text">Bilans </h6>
            <h6>@Html.DisplayFor(m => m.CompanyId)</h6>
        </div>
    </div>
</div>

<br />

<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <table class="table table-striped border">
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.RaportYear)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.AktywaTrwale)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.AktywaObrotowe)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.AktywaRazem)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.KapitalWlasnyAkcjonariuszyJednostkiDominujacej)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.UdzialyNiekontrolujace)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.ZobowiazaniaDlugoterminowe)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.ZobowiazaniaKrotkoterminowe)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.BalanceColumnDescription.PasywaRazem)
            </th>
        </tr>
        @foreach (var raport in Model.BalanceRaports)
        {
    <tr>
        <td align="center">
            @Html.DisplayFor(r => raport.RaportYear)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.AktywaTrwale)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.AktywaObrotowe)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.AktywaRazem)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.KapitalWlasnyAkcjonariuszyJednostkiDominujacej)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.UdzialyNiekontrolujace)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZobowiazaniaDlugoterminowe)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZobowiazaniaKrotkoterminowe)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.PasywaRazem)
        </td>
    </tr>
        }
    </table>
</div>

HomeTrader.Web/Views/Details/CashFlow.cshtml
@model HomeTrader.Models.DetailsVM.CashFlowVM
@{
    ViewData["Title"] = "CashFlow";
}

<h6>Przepływy</h6>
<br />
<div class="row">
    <partial name="_DetailsMenuButtons" model="@Model.CompanyId"/>
</div>
<br />
<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <div class="row">
        <div class="col-6">
            <h6 class="text">Przepływy gotówki </h6>
            <h6>@Html.DisplayFor(m => m.CompanyId)</h6>
        </div>
    </div>
</div>

<br />

<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <table class="table table-striped border">
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.CashFlowColumnDescription.RaportYear)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.CashFlowColumnDescription.PrzeplywyZDzialalnosciOperacyjnej)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.CashFlowColumnDescription.PrzeplywyZDzialalnosciInvestycyjnej)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.CashFlowColumnDescription.PrzeplywyZDzialalnosciFinansowej)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.CashFlowColumnDescription.PrzeplywyRazem)
            </th>
        </tr>
        @foreach (var raport in Model.CashFlowRaports)
        {
            <tr>
                <td align="center">
                    @Html.DisplayFor(r => raport.RaportYear)
                </td>
                <td align="center">
                    @Html.DisplayFor(r => raport.PrzeplywyZDzialalnosciOperacyjnej)
                </td>
                <td align="center">
                    @Html.DisplayFor(r => raport.PrzeplywyZDzialalnosciInvestycyjnej)
                </td>
                <td align="center">
                    @Html.DisplayFor(r => raport.PrzeplywyZDzialalnosciFinansowej)
                </td>
                <td align="center">
                    @Html.DisplayFor(r => raport.PrzeplywyRazem)
                </td>
            </tr>
        }
    </table>
</div>

HomeTrader.Web/Views/Details/Index.cshtml
@model HomeTrader.Models.DetailsVM.IndexVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h6>Szczegoly spolki o ID : @Html.DisplayFor(m => m.CompanyId)</h6>
<br />
<div class="row">
    <partial name="_DetailsMenuButtons" model="@Model.CompanyId" />
</div>
<br />

<div>
    <h6> @Html.DisplayNameFor(c => c.Company.Id) : @Html.DisplayFor(c => c.Company.Id)</h6>
    <h6>@Html.DisplayNameFor(c => c.Company.Name) : @Html.DisplayFor(c => c.Company.Name)</h6>
    <h6>@Html.DisplayNameFor(c => c.Company.ISIN) : @Html.DisplayFor(c => c.Company.ISIN)</h6>
    <h6>@Html.DisplayNameFor(c => c.Company.Ticker) : @Html.DisplayFor(c => c.Company.Ticker)</h6>
    <h6>@Html.DisplayNameFor(c => c.Company.Index) : @Html.DisplayFor(c => c.Company.Index)</h6>
    <h6>@Html.DisplayNameFor(c => c.Company.CompanyDescription) : @Html.DisplayFor(c => c.Company.CompanyDescription)</h6>
</div>

HomeTrader.Web/Views/Details/ProfitAndLose.cshtml
@model HomeTrader.Models.DetailsVM.ProfitAndLoseVM
@{
    ViewData["Title"] = "ProfitAndLose";
}

<h6>Balans</h6>
<br />
<div class="row">
    <partial name="_DetailsMenuButtons" model="@Model.CompanyId" />
</div>
<br />
<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <div class="row">
        <div class="col-6">
            <h6 class="text">Zysk i strata </h6>
            <h6>@Html.DisplayFor(m => m.CompanyId)</h6>
        </div>
    </div>
</div>

<br />

<div class="border-bottom border-white shadow rounded-lg" style="background-color: #ededed">
    <table class="table table-striped border">
        <tr>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.RaportYear)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.PrzychodyZeSprzedazy)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.ZyskZeSprzedazy)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.ZyskOperacyjny)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.ZyskZDzialalnosciGospodarczej)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.ZyskPrzedOpodatkowaniem)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.ZyskNetto)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.ZyskNettoAkcjonariuszyJednostkiDominujacej)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.ProfitAndLoseDescription.EBITDA)
            </th>


        </tr>
        @foreach (var raport in Model.ProfitAndLoseRaports)
        {
    <tr>
        <td align="center">
            @Html.DisplayFor(r => raport.RaportYear)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.PrzychodyZeSprzedazy)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZyskZeSprzedazy)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZyskOperacyjny)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZyskZDzialalnosciGospodarczej)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZyskPrzedOpodatkowaniem)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZyskNetto)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.ZyskNettoAkcjonariuszyJednostkiDominujacej)
        </td>
        <td align="center">
            @Html.DisplayFor(r => raport.EBITDA)
        </td>
    </tr>
        }
    </table>
</div>

HomeTrader.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HomeTrader.Web/Views/Shared/_CompaniesMenuButtons.cshtml
<div class="col-2">
    <a asp-area="" asp-controller="Company" asp-action="Company" class="btn btn-secondary btn-sm">Wig</a>
</div>
<div class="col-2">
    <a  asp-controller="Company" asp-action="IndexSort" asp-route-id="1" class="btn btn-secondary btn-sm">Wig20</a>
</div>
<div class="col-2">
    <a  asp-controller="Company" asp-action="IndexSort" asp-route-id="2" class="btn btn-secondary btn-sm">Wig40</a>
</div>
<div class="col-2">
    <a  asp-controller="Company" asp-action="IndexSort" asp-route-id="3" class="btn btn-secondary btn-sm">sWig80</a>
</div>

HomeTrader.Web/Views/Shared/_DetailsMenuButtons.cshtml
@model int

<div class="col-2">
    <a asp-area="" asp-controller="Details" asp-action="Company" asp-route-id="@Model" class="btn btn-secondary btn-sm">Działalność spółki</a>
</div>
<div class="col-2">
    <a asp-area="" asp-controller="Details" asp-action="" class="btn btn-secondary btn-sm">Wskaźniki</a>
</div>
<div class="col-2">
    <a asp-area="" asp-controller="Details" asp-action="GetCashFlow" asp-route-id="@Model" class="btn btn-secondary btn-sm">Przepływy</a>
</div>
<div class="col-2">
    <a asp-area="" asp-controller="Details" asp-action="GetBalance" asp-route-id="@Model" class="btn btn-secondary btn-sm">Balans</a>
</div>
<div class="col-2">
    <a asp-area="" asp-controller="Details" asp-action="GetProfitAndLose" asp-route-id="@Model" class="btn btn-secondary btn-sm">Zysk/strata</a>
</div>

HomeTrader.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HomeTrader</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HomeTrader</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">Dane ze swiata</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="">Portfel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Company" asp-action="Index">Spolki GPW</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Details" asp-action="Index">Analiza spolek</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - HomeTrader - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>